name: 'dbt Setup'
description: 'Setup environment for dbt operations with BigQuery'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.x'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dbt
      run: |
        pip install dbt-bigquery

    - name: Set up environment variables and write service account key
      env:
        CICD_SERVICE_ACCOUNT: ${{ secrets.CICD_SERVICE_ACCOUNT }}
      run: |
        printf "%s" "${CICD_SERVICE_ACCOUNT}" > /tmp/service_account.json

    - name: Create dbt profiles directory
      run: mkdir -p ~/.dbt

    - name: Generate profiles.yml
      env:
        CICD_DATASET: ${{ secrets.CICD_DATASET }}
        CICD_LOCATION: ${{ secrets.CICD_LOCATION }}
        CICD_PRIORITY: ${{ secrets.CICD_PRIORITY }}
        CICD_PROJECT: ${{ secrets.CICD_PROJECT }}
      run: |
        cat <<EOF > ~/.dbt/profiles.yml
        sethbox:
          target: ci
          outputs:
            ci:
              dataset: "$CICD_DATASET"
              keyfile: "/tmp/service_account.json"
              location: "$CICD_LOCATION"
              priority: "$CICD_PRIORITY"
              project: "$CICD_PROJECT"
              type: bigquery
              method: service-account
              job_execution_timeout_seconds: 300
              job_retries: 1
              threads: 16
        EOF

    - name: Display profiles.yml for debugging
      run: |
        cat ~/.dbt/profiles.yml
