name: Persist dbt Artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Explicitly grant write permissions to the GITHUB_TOKEN

jobs:
  persist_artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false  # Disable automatic token persistence

    - name: Setup dbt Environment
      uses: ./.github/actions/dbt-setup
      with:
        python-version: '3.x'

    - name: Run dbt to generate artifacts
      run: |
        dbt deps --profiles-dir ~/.dbt
        dbt compile --profiles-dir ~/.dbt
        dbt docs generate --profiles-dir ~/.dbt

    - name: Checkout artifacts branch
      run: |
        git fetch origin
        if git branch -a | grep 'remotes/origin/artifacts'; then
          git checkout artifacts
          git merge origin/main --no-edit || true
        else
          git checkout -b artifacts
        fi

    - name: Create artifacts directory
      run: |
        mkdir -p artifacts

    - name: Copy new artifacts
      run: |
        cp target/manifest.json artifacts/manifest.json
        cp target/catalog.json artifacts/catalog.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add artifacts/manifest.json artifacts/catalog.json
        git commit -m "Update artifacts"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git artifacts
