name: Persist dbt Manifest

on:
  push:
    branches:
      - main

jobs:
  persist_manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dbt
      run: |
        pip install dbt-bigquery

    - name: Set up environment variables and write service account key
      run: |
        echo "${{ secrets.CICD_SERVICE_ACCOUNT }}" > /tmp/service_account.json
      env:
        CICD_DATASET: ${{ secrets.CICD_DATASET }}
        CICD_LOCATION: ${{ secrets.CICD_LOCATION }}
        CICD_PRIORITY: ${{ secrets.CICD_PRIORITY }}
        CICD_PROJECT: ${{ secrets.CICD_PROJECT }}

    - name: Create dbt profiles directory
      run: mkdir -p ~/.dbt

    - name: Copy profiles.yml to dbt directory
      run: cp .ci/profiles.yml ~/.dbt/profiles.yml

    - name: Run dbt to generate manifest
      env:
        CICD_DATASET: ${{ secrets.CICD_DATASET }}
        CICD_SERVICE_ACCOUNT: /tmp/service_account.json
        CICD_LOCATION: ${{ secrets.CICD_LOCATION }}
        CICD_PRIORITY: ${{ secrets.CICD_PRIORITY }}
        CICD_PROJECT: ${{ secrets.CICD_PROJECT }}
      run: |
        dbt deps --profiles-dir ~/.dbt
        dbt compile --profiles-dir ~/.dbt

    - name: Checkout manifests branch
      run: |
        git fetch origin
        git checkout -b manifests origin/manifests || git checkout manifests

    - name: Copy new manifest
      run: |
        cp target/manifest.json manifests/previous_manifest.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add manifests/previous_manifest.json
        git commit -m "Update previous manifest"
        git push origin manifests
